arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart

synthetic-package: false
output-dir: lib/l10n/generated

untranslated-messages-file: lib/l10n/untranslated.txt
nullable-getter: false
preferred-supported-locales:
  - en
  - zh_Hant_TW

use-deferred-loading: false